version: '2'
services:
  cybertech_db:
    image: mysql:8
    container_name: cybertech
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cybertech         